### ISSUE TITLE
Cura can not read Blender

### ISSUE THREAD

**Issue by RogueWaves** [awiegel/CuraBlender#7]
Blender 3.0 and Cura 4.12.1 

Cura loads Blender file then wait several minutes, while it's loading, finally the fatal error....happens on five different files 
Posted it on Cura Community submited cure.log and think it lies in the plugins....

bill_gallagher@live.com
further info it needed

**Comment by awiegel** [comment]
Just downloaded both Blender 3.0 and Cura 4.12.1 and everything works fine for me.

Basically, what this plugin does is converting a .blend file internally with Blender into the specified file format (.stl, .obj, .x3d, .ply - which can be selected through 'Extensions -> CuraBlender -> Settings').

Did you try exporting your .blend files directly with Blender into one of the four supported file formats and then loading the newly converted file into Cura? If this does not work the problem is not with the plugin but more with Blender not handling such 'complex' objects. Also, did you try loading a very simple .blend object like a cube into Cura?

Please try this out and let me know if this information helped.

**Comment by RogueWaves** [comment]
Thanks for quick reply
In Cura setting all file types are enabled

simple default cube in Blender will not load in Cura

Writing file out to OBJ import into Cura is Fine

In Cura Debug Blender "PATH"  window shows 
  1) Path indicator for Blender.exe file but checking with file explorer, win10, does not exist......how do set correct path?

  2) select  "Open Text File"  ask for Path to Blender

Cura has wrong path to Blender causing not loading file....My thought

**Comment by RogueWaves** [comment]
UPDATE
Uninstalled Blender and Cura
rebooted win 10
installed above
Cura not reading Blender files
Path in Cura Checks out fine

Cura reads export file from Blender, if changed, Cura ask want to reload
and it does

**Comment by RogueWaves** [comment]
I uninstalled blender and Cura
Rebooted win 10
Install both of them
Cura unable to read blender file

Exported model to OBJ in Blender 
Cura read OBJ file
Changed properties in OBJ and saved
Cure prompt want to reload  file
Cura reload file and fine

Problem Cura not reading Blender files 


Thanks for your help



I personally approve this email
             Bill Gallagher

Resident of Milton
Membership/Volunteer in:
Milton Yacht club
Neponset River watershed
U S Coast Guard Aux 
Milton historical Society
Shriners hospital 
New England Estuarine Society
SeaGrant MIT
NOAA Stellwagen Bank

**Comment by awiegel** [comment]
Because it works fine for me with the same Cura/Blender versions and Windows 10 I can only think of two problems:
1. Since you export your models to .obj, have you tried the setting:
   'Extensions -> CuraBlender -> Settings -> Select Import Type -> .obj'?
   Maybe there are problems with .stl which should be selected by default.
2. Have you checked your path to Blender (blender.exe)?
    Also, in case of multiple installations of Blender, is the right version selected?
   You could also try to install Blender on a different path (I use the path shown in the picture which works fine right after installation without me having to change anything).
![blender_path](https://user-images.githubusercontent.com/71146780/146361343-c773b767-cd8f-476c-87e2-05d16d8f7a88.png)
 
I really hope this will solve your problem.

All the best
Alex

**Comment by RogueWaves** [comment]
Well, STL and OBJ works  fine but Blender still a issue...Strange Problem ......It's workable
thanks for the input
