### ISSUE TITLE
Cura path to Blender?

### ISSUE THREAD

**Issue by lavrentius-dev** [awiegel/CuraBlender#8]
Hi Alex, thank you for this great plugin. I am having difficulties setting a path to Blender when it is installed as a Windows app from the Microsoft Store. I set it once and it worked fine for a while--until the app received an update. Is there a known workaround for this? The blender windows app can be launched by pressing Win+R and typing 'blender' in the popup Run dialog, so I suppose there is a way to quickly find the executable path for any app. Thanks.

**Comment by awiegel** [comment]
Hi,

I'm glad you enjoy this plugin.

Dealing with the windows app store is really complicated due to security reasons, e.g. you can not access "C:\Program Files\WindowsApps" directly. The only option I know to get the path to the installed Blender app is through the task manager.
For this:
1. Open the Blender app.
2. Open the task manager and under processes right-click on Blender X.X.X.X (any version) and click on "Extend".
3. On the underlying "Blender" process you can open the file path via right-click.
4. Manually add this path in Cura under "Extensions" -> "CuraBlender" -> "Debug Blenderpath".

The manually set path should remain even after restarting Cura.

Seems like you have to repeat this procedure every time a new update in the windows app store arrives.
An alternative would be to install Blender directly through their website https://www.blender.org/download/.
If installed under the default path this plugin should be able to find it automatically in most cases.

Let me know if this works for you.

All the best
Alex

**Comment by Harstrup** [comment]
Sendt fra min iPhone

Den 8. okt. 2022 kl. 10.44 skrev Alexander Wiegel ***@***.***>:

﻿

Closed #8<https://github.com/awiegel/CuraBlender/issues/8> as completed.
